/*
Auto-generated by: https://github.com/pmndrs/gltfjsx

https://www.cgtrader.com/free-3d-models/sports/game/basket-ball-b0b4aa95-8ce2-4366-987a-99c838208d3b

*/

import { useGLTF } from "@react-three/drei";

export function Basketball(props) {
  const { nodes, materials } = useGLTF("/basketball.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere_1.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere_2.geometry}
        material={materials["Material.002"]}
      />
    </group>
  );
}

useGLTF.preload("/basketball.glb");
