/*
Initially auto-generated by: https://github.com/pmndrs/gltfjsx

https://www.cgtrader.com/free-3d-models/sports/game/basket-ball-b0b4aa95-8ce2-4366-987a-99c838208d3b

*/

import { useRef } from "react";

import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Basketball(props) {
  const { nodes, materials } = useGLTF("/basketball.glb");

  const mesh = useRef(null);

  useFrame((_state, delta) => {
    mesh.current.rotation.y -= delta / 5;
    mesh.current.rotation.x -= delta / 5;
    mesh.current.rotation.z -= delta / 5;
  });

  return (
    <group ref={mesh} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere_1.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere_2.geometry}
        material={materials["Material.002"]}
      />
    </group>
  );
}

useGLTF.preload("/basketball.glb");
